### ISSUE TITLE
Add the ability to change the members of the cluster

### ISSUE THREAD

**Issue by schmidtfx** [bakwc/PySyncObj#16] opened 2016-07-20 11:57 UTC
The raft protocol also describes membership changes inside of the cluster. Are there any thoughts about adding this very useful feature into PySyncObj?

**Comment by bakwc** [comment] 2016-07-20 14:42
Hi, dynamic cluster size configuration will be added very soon, may be on this weekend. Close as a duplicate of #8

**Closed by bakwc** 2016-07-20 14:42 UTC

**Comment by bakwc** [comment] 2016-07-24 22:08
Done.
